<?php
$sql  = "SELECT res_files_passwords.*  FROM res_files_passwords WHERE 1 ORDER BY id DESC";
$k = $con->query($sql);
$data = array();
if ($k->num_rows > 0) {
    while ($u = $k->fetch_assoc()) $data[] = $u;
}
?>
<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Files</h1>
    <p class="mb-4">list of passwords files change, insert, delete and update! </p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Passwords files
                <button class="ml-5 btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="addNewFileInList()">Add new file</button>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>File ID</th>
                            <th>Title</th>
                            <th>Password</th>
                            <th>User ID</th>
                            <th>created on</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php
                        foreach ($data as $item) {
                        ?>
                            <tr>
                                <td><?php echo $item['id']; ?></td>
                                <td><?php echo $item['file_id']; ?></td>
                                <td><?php echo $item['file_title']; ?></td>
                                <td><?php echo $item['file_pass']; ?></td>
                                <td><?php echo $item['user'] == 0 ? 'Admin' : $item['user']; ?></td>
                                <td><?php echo $item['createdAt'] ?></td>
                                <td style="min-width: 248px">
                                    <?php
                                    if (!$userAction)  echo "Low level admin action is prohibited";
                                    else { ?>
                                        <button class="btn btn-danger" onclick="handleDeleteFile(<?php echo $item['id']; ?>)">Delete</button>
                                        <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="handleEditFile({file_id:<?php echo $item['file_id']; ?>, filename: '<?php echo $item['file_title']; ?>', password:'<?php echo $item['file_pass']; ?>'})">Edit</button>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>File ID</th>
                            <th>Title</th>
                            <th>Password</th>
                            <th>User ID</th>
                            <th>created on</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

</div>