<?php
$sql  = "SELECT * FROM res_user_pass_manager WHERE 1 ORDER BY `id` DESC;";
$k = $con->query($sql);
$data = array();
if ($k->num_rows > 0) {
    while ($u = $k->fetch_assoc()) $data[] = $u;
}
?>
<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Users Manager</h1>
    <p class="mb-4">Users list manager.</p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Passwords files
                    <?php if ($userAction) { ?><button class="ml-5 btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="addNewUser()">Add new file</button><?php } ?>
                </h6>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>username</th>
                            <th>email</th>
                            <th>created on</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>username</th>
                            <th>email</th>
                            <th>created on</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php
                        foreach ($data as $item) {
                        ?>
                            <tr>
                                <td><?php echo $item['id']; ?></td>
                                <td><?php echo $item['username']; ?></td>
                                <td><?php echo $item['email']; ?></td>
                                <td><?php echo date_format(date_create($item['createdAt']), 'd M Y'); ?></td>
                                <td style="min-width: 210px">
                                    <?php if (!$userAction) echo 'Low level admin action is prohibited';
                                    else { ?><button class="btn btn-danger" onclick="handleUserDelete(<?php echo $item['id']; ?>)">Delete</button>
                                        <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="handleEditUser({username: '<?php echo $item['username']; ?>' ,password: '<?php echo $item['password']; ?>' , email: '<?php echo $item['email']; ?>' ,id: <?php echo $item['id']; ?>})">Edit User</button>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>